parameters:
  runIntegrationTests:

steps:
- task: UsePythonVersion@0
  displayName: Use Python $(python.version)
  inputs:
    versionSpec: '$(python.version)'
    architecture: '$(python.architecture)'

- powershell: |
    echo "Installing FS-iSCSITarget-Server"
    Install-WindowsFeature -Name FS-iSCSITarget-Server

    # Allow connection on loopback interface.
    Set-ItemProperty -Path 'HKLM:\SOFTWARE\Microsoft\iSCSI Target' -Name AllowLoopBack -Value 1

    echo "Starting MsiSCSI"
    Start-Service msiscsi
    $retry = 10
    do
    {
      $count = (Get-Service msiscsi | ? {$_.status -eq "Running"}).count
      $retry--
      sleep -Milliseconds 500
    } until ($count -Eq 0 -or $retry -Eq 0)

    $service = Get-Service msiscsi
    if ($service.Status -Ne "Running") {
      throw "msiscsi not running"
    }

    echo "Configuring Firewall"
    Get-NetFirewallServiceFilter -Service msiscsi | Enable-NetFirewallRule

    echo "Configuring RAMDisk"
    New-IscsiVirtualDisk -ComputerName localhost -Path ramdisk:RAMDISK1.vhdx -Size 1GB
    New-IscsiServerTarget Target1 -ComputerName localhost -InitiatorId "IQN:*"
    Add-IscsiVirtualDiskTargetMapping -ComputerName localhost -TargetName Target1 -Path ramdisk:RAMDISK1.vhdx -Lun 1

    echo "Connecting to iSCSI"
    $ip = (Get-NetIPAddress -AddressFamily IPv4).ipaddress[0]
    New-IscsiTargetPortal -TargetPortalAddress $ip
    Get-IscsiTarget | Connect-IscsiTarget

    echo "Configuring disk"
    Get-IscsiConnection | Get-Disk | Set-Disk -IsOffline $False
    Get-IscsiConnection | Get-Disk | Initialize-Disk -PartitionStyle MBR
    Get-IscsiConnection | Get-Disk | New-Partition -UseMaximumSize -DriveLetter R
    Format-Volume -DriveLetter R -NewFileSystemLabel Temp -FileSystem NTFS
  displayName: Test

- powershell: |
    Invoke-WebRequest -Uri https://go.microsoft.com/fwlink/?linkid=2026036 -OutFile adksetup.exe
    ./adksetup.exe /features OptionId.WindowsPerformanceToolkit /log adk-setup.log /ceip off /installpath "C:\Program Files (x86)\Windows Kits\10\"
    # Wait for install to complete.
    python -c "
    import os, time
    start = time.time()
    last = start
    while last - start < 60:
     if os.path.exists('C:/Program Files (x86)/Windows Kits/10/Windows Performance Toolkit/wpr.exe'):
      break
     print('Waiting...')
     time.sleep(2)
     last = time.time()
    "
    Get-Content adk-setup.log
  displayName: ADK Setup

- bash: pip install --upgrade setuptools tox
  displayName: Install Tox

- script: mkdir traces
  displayName: Make trace output directory

- script:
    tox -e py -- -m unit --junit-xml=junit/unit-test.xml
    --use-wpr
    --wpr-path="C:\Program Files (x86)\Windows Kits\10\Windows Performance Toolkit\wpr.exe"
    --wpr-profile=GeneralProfile.verbose
    --wpr-profile=CPU.verbose
    --wpr-output=traces/wpr-result.etl
  env:
    TEMP: "R:\\"
  displayName: Tox run unit tests

- script:
    tracerpt -l traces/wpr-result.etl -export traces/providers.man
  displayName: Generate trace provider manifest

- task: PublishBuildArtifacts@1
  displayName: 'Publish trace results'
  inputs:
    pathtoPublish: traces
    artifactName: wpr-result-$(python.version)-$(python.architecture).etl
  condition: succeededOrFailed()

- ${{ if eq(parameters.runIntegrationTests, 'true') }}:
  - powershell: |
      # Fix Git SSL errors
      pip install certifi tox
      python -m certifi > cacert.txt
      $env:GIT_SSL_CAINFO = $(Get-Content cacert.txt)

      # Shorten paths to get under MAX_PATH or else integration tests will fail
      # https://bugs.python.org/issue18199
      subst T: $env:TEMP
      $env:TEMP = "T:\"
      $env:TMP = "T:\"

      tox -e py -- -m integration -n 3 --duration=5 --junit-xml=junit/integration-test.xml
    displayName: Tox run integration tests

- task: PublishTestResults@2
  displayName: Publish Test Results
  inputs:
    testResultsFiles: junit/*.xml
    testRunTitle: 'Python $(python.version)'
  condition: succeededOrFailed()
